-- Fix MonthlyReview Table Schema
-- Run this in Supabase SQL Editor

-- 1. Drop existing table (Safe only if empty, which we verified)
DROP TABLE IF EXISTS "MonthlyReview";

-- 2. Re-create with correct columns
CREATE TABLE "MonthlyReview" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "year" integer NOT NULL,
    "month" integer NOT NULL,
    "summary" text,
    "highlights" jsonb DEFAULT '[]'::jsonb,
    "challenges" jsonb DEFAULT '[]'::jsonb,
    "lessons" jsonb DEFAULT '[]'::jsonb,
    "next_steps" jsonb DEFAULT '[]'::jsonb,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    
    -- Ensure one review per month
    CONSTRAINT "monthly_review_year_month_key" UNIQUE ("year", "month")
);

-- 3. Enable RLS (Optional but good practice)
ALTER TABLE "MonthlyReview" ENABLE ROW LEVEL SECURITY;

-- 4. Allow access (Adjust policies as needed, here we allow all for now for simplicity in dev)
CREATE POLICY "Enable all access" ON "MonthlyReview" FOR ALL USING (true) WITH CHECK (true);
